# Site settings
title: AI Generated Floor Plans
description: 'The future of floor planning using Artificial Intelligence' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
domain: d7057e-ai-generated-floor-plans.github.io
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://d7057e-ai-generated-floor-plans.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: # TODO: Add logo
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: # TODO: Add dark-mode logo
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Students from D7057E # add your name
author-pic: branding/MVM-symbol.svg # add your profile picture
about-author: We are a team of 10 students who have embarked on an exciting journey to revolutionize the way we envision floor plans, with the power of artificial intelligence.

# Contact links
email: jonstn-9@student.ltu.se # Add your Email address
phone: # Add your Phone number
website: # Add your website
linkedin: # Add your Linkedin handle
github: D7057E-AI-Generated-Floor-Plans # Add your Github handle
twitter: # Add your Twitter handle
bandcamp: # Add your Bandcamp username
stackoverflow: # Add your stackoverflow account

# Newsletter
mailchimp: 

# Tracker
analytics:
fbadmin:

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate-v2

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]